#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=BuildTools.jar
BUILDTOOLS_JAR = BuildTools.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$BUILDTOOLS_JAR" ]; then
	wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
	java -jar $BUILDTOOLS_JAR
fi

